In [3]:
import pandas as pd

In [4]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [75]:
train.head(50)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,NaN,Q
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S

In [12]:
train = pd.get_dummies(train, columns=['Sex', 'Embarked'], drop_first=True) # Encode these columns with 0 and 1

KeyError: "None of [Index(['Sex', 'Embarked'], dtype='object')] are in the [columns]"

In [18]:
train.head()
train["Sex_male"] = train["Sex_male"].astype(int)
train["Embarked_Q"] = train["Embarked_Q"].astype(int)
train["Embarked_S"] = train["Embarked_S"].astype(int)
train.head()


train.drop("Name", axis =1)

train['Has_Cabin'] = train['Cabin'].notna().astype(int)

In [29]:
tr = train.copy()
tr = tr.drop(["Cabin"], axis=1)
tr = tr.drop(["Name"], axis=1)
tr = tr.drop(["Ticket"], axis=1)

In [ ]:
# EDA
col = tr.columns
tr.info()       ## We see that there are missing values for age. Handle with data imputation.
missing_count = tr.isnull().sum()

import seaborn as sns 
import numpy as np

# Visualizations 

tr.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Age          714 non-null    float64
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   Fare         891 non-null    float64
 7   Sex_male     891 non-null    int32
 8   Embarked_Q   891 non-null    int32
 9   Embarked_S   891 non-null    int32
 10  Has_Cabin    891 non-null    int32
dtypes: float64(2), int32(4), int64(5)
memory usage: 62.8 KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S,Has_Cabin
0,1,0,3,22.0,1,0,7.2500,1,0,1,0
1,2,1,1,38.0,1,0,71.2833,0,0,0,1
2,3,1,3,26.0,0,0,7.9250,0,0,1,0
3,4,1,1,35.0,1,0,53.1000,0,0,1,1
4,5,0,3,35.0,0,0,8.0500,1,0,1,0

In [6]:
# Model Selection 

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [10]:
X_train = train_num.drop(['Survived', 'PassengerId'], axis=1)
y_train = train_num["Survived"]
X_test = test_num.drop(["PassengerId"], axis=1)

In [11]:
# Needs numeric only

In [12]:
# Imputation

imputer = SimpleImputer(missing_values=np.nan, strategy="median")
X_train_num = pd.DataFrame(imputer.fit_transform(X_train), columns = X_train.columns)
X_test_num = pd.DataFrame(imputer.transform(X_test), columns = X_test.columns)

In [13]:
# Scaling
scaler = StandardScaler()

X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train_num), columns = X_train_num.columns)
X_test_scaled = pd.DataFrame(scaler.transform(X_test_num), columns = X_test_num.columns)

In [14]:
# Modeling

### Logistics Regression 

log = LogisticRegression() 

log.fit(X_train_scaled, y_train)

LogisticRegression()

In [15]:
y_pred = log.predict(X_test_scaled)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [20]:
### Decision Tree Classifier 

from sklearn.tree import DecisionTreeClassifier

In [51]:
DecisionTree = DecisionTreeClassifier(max_depth=5)

In [52]:
DecisionTree.fit(X_train_scaled, y_train)

DecisionTreeClassifier(max_depth=5)

In [53]:
tree_predict = DecisionTree.predict(X_test_scaled)

In [25]:
### KNN Classification 

from sklearn.neighbors import KNeighborsClassifier

In [26]:
knn = KNeighborsClassifier()

In [27]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [28]:
knn_predict = knn.predict(X_test_scaled)

In [32]:
### Support Vector Machine 

from sklearn.svm import SVC

In [ ]:
support = SVC(kernel="poly")

support.fit(X_train_scaled, y_train)
sp_pred = support.predict(X_test_scaled)

0.6483253588516746

In [105]:
## Employ Cross Validation

In [35]:
from sklearn.model_selection import cross_val_score

In [55]:
# CV 

log_scores = cross_val_score(log, X_train_scaled, y_train, cv=5) ## Noticable improvements 
tree_scores = cross_val_score(DecisionTree, X_train_scaled, y_train, cv=5)
knn_scores = cross_val_score(knn, X_train_scaled, y_train, cv=5)
svm_scores = cross_val_score(support, X_train_scaled, y_train, cv=5)

In [56]:
print("Accuracy scores for each fold (Logistic):", log_scores)
print("Accuracy scores for each fold (Tree):", tree_scores)
print("Accuracy scores for each fold (KNN):", knn_scores)
print("Accuracy scores for each fold (SVM):", svm_scores)

Accuracy scores for each fold (Logistic): [0.6424581  0.68539326 0.73033708 0.71910112 0.70786517]
Accuracy scores for each fold (Tree): [0.6424581  0.64606742 0.73595506 0.73595506 0.74719101]
Accuracy scores for each fold (KNN): [0.65363128 0.64044944 0.70786517 0.75842697 0.6741573 ]
Accuracy scores for each fold (SVM): [0.63687151 0.69101124 0.70224719 0.74157303 0.75842697]

In [58]:
# Print MAX scores

print("Maximum score (Log):", max(log_scores))
print("Maximum score (Tree):", max(tree_scores))
print("Maximum score (KNN):", max(knn_scores))
print("Maximum score (SVM):", max(svm_scores))

Maximum score (Log): 0.7303370786516854
Maximum score (Tree): 0.7471910112359551
Maximum score (KNN): 0.7584269662921348
Maximum score (SVM): 0.7584269662921348

In [ ]:
# We see that the KNN and SVM models both have the highest max scores from Cross Validation. This would be for the same default random state.

In [73]:
# Feature importance (i.e what are the best features to use for the model)

from sklearn.feature_selection import RFE

selector = RFE(DecisionTree, n_features_to_select = 2)
selector.fit(X_train_scaled, y_train)
selected_features = X_train_scaled.columns[selector.support_]
print("Selected Features:", list(selected_features))

Selected Features: ['Pclass', 'Fare']

In [60]:
# Pipeline (This will automate the Imputation, Scaling, and Feature Importance for different models.)